# Generated by Django 5.1.3 on 2024-11-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
