# Generated by Django 5.1.3 on 2024-11-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0002_categorymodel_menuitem_commentmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='MenuItemModel',
        ),
    ]
